### ISSUE TITLE
iframe  exception in console

### ISSUE THREAD

**Issue by morandalex** [oktadeveloper/okta-vue-auth-example#2]
Hello all,

I installed this app on my server. The "npm run dev" command works fine.
I created also an account on okta and updated auth.js file as explained in [here](https://developer.okta.com/blog/2017/09/14/lazy-developers-guide-to-auth-with-vue)

The issue is the following exception launched in the developer console with the result that i cannot autenticate myself.

> Refused to display 'https://{**MYOKTADOMAIN**}.oktapreview.com/error/404?fromURI=%2Foauth2%2Fv1%2Fauthorize%3Fclient_id%3D{**CLIENTID**}%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8080%26response_type%3Did_token%2520token%26response_mode%3Dokta_post_message%26state%3DuifCspEhBZh1tIonaBeWejnjz8KX9devstqt7Cn8SlAaf17elNSsovuG8Kk022VW%26nonce%3DkM9nAzR5BWF6A1vLbHc94MUwdFnjAnT4rSVlWGwNu69dlaPqe9Qv9r6JMu5AkMyI%26prompt%3Dnone%26sessionToken%3D20111IvBufhvEdENA1OSF3_-ax_Qyze7LgWa7TJGYYeYyVtoQHMR-Dp%26scope%3Dopenid%2520email%2520profile' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

How to solve?

Really thanks for your time and help.

**Comment by mraible** [comment]
Did you setup Okta to have the `redirect_uri` from your server? Is your server still localhost, or something else?

**Comment by morandalex** [comment]
I don't know exactly what you intend for `redirect_uri` .

I didn't insert the word _localhost_ , but my IP address.
So I have http://{my-ip-server-address}/8080

Following the okta configuration for trusted origins:
![image](https://user-images.githubusercontent.com/9484568/31722245-e6145ce0-b41b-11e7-8981-f8d928385b59.png)
Following the okta configuration for the application that I created:
![image](https://user-images.githubusercontent.com/9484568/31722350-25a78e2c-b41c-11e7-8f33-dc029b857acb.png)

I am using NGINX server.

**Comment by omgitstom** [comment]
Make sure you didn't accidentally copy the *-admin from the URL for your org...

I've seen a lot of people do this and it will cause the iframe error because the admin domain is protected from click-jacking.  Sometimes the widget / authjs library will use an iframe if it is doing postMessage.
